name: hello world workflow

on:
  push:
    paths:
      - '.github/workflows/hello.yml'

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello
        run: echo "Hello Github actions"